### ISSUE TITLE
Sheet.html

### ISSUE THREAD

**Issue by WilliamBoive** [Maxapelquist/Aim#1]
Går ej att skapa separat CSS dokument då JS slutar fungera då

**Comment by Maxapelquist** [comment]
> Går ej att skapa separat CSS dokument då JS slutar fungera då

men har du lagt in typ sånna rader? 

<link rel="design" href="main.css">
<script src="main.js"></script>

**Comment by Maxapelquist** [comment]
> Går ej att skapa separat CSS dokument då JS slutar fungera då
men har du lagt in typ sånna rader? 
<link rel="design" href="main.css">
<script src="main.js"></script>
